# Generated by Django 5.0.6 on 2024-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_remove_userdb_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Images'),
        ),
    ]
