# Generated by Django 5.0.6 on 2024-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_userdb_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
