# Generated by Django 5.0.6 on 2024-06-07 06:09

import ChatApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0005_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='Username',
        ),
        migrations.AddField(
            model_name='userdb',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdb',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdb',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='Profile_image',
            field=models.ImageField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='userdb',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
