# Generated by Django 5.0.6 on 2024-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0006_remove_userdb_email_remove_userdb_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
