# Generated by Django 5.0.6 on 2024-06-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0007_alter_userdb_date_joined_alter_userdb_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
