# Generated by Django 5.0.6 on 2024-06-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0011_chatnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
