# Generated by Django 5.0.6 on 2024-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0013_alter_chatmodelpvt_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
