# Generated by Django 5.0.6 on 2024-06-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0014_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
