# Generated by Django 5.0.6 on 2024-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0021_alter_user_details_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
