# Generated by Django 5.0.6 on 2024-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0023_user_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
    ]
