# Generated by Django 5.0.6 on 2024-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0025_user_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_image',
            field=models.ImageField(blank=True, default='logo/default.png', null=True, upload_to='Profile_Images'),
        ),
    ]
