# Generated by Django 5.0.6 on 2024-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0026_alter_user_details_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Bio',
            field=models.CharField(blank=True, default='Connectify', max_length=50, null=True),
        ),
    ]
