# Generated by Django 5.0.6 on 2024-08-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0029_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
