# Generated by Django 5.0.6 on 2024-08-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0032_rename_notification_notificationdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdb',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdb',
            name='receiver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdb',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
