# Generated by Django 5.0.6 on 2024-08-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0034_remove_notificationdb_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdb',
            name='roomname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdb',
            name='threadname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
