# Generated by Django 5.0.6 on 2024-08-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0035_alter_notificationdb_roomname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationDB',
        ),
    ]
