# Generated by Django 5.0.6 on 2024-08-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0038_notificationdb_receiver_alter_notificationdb_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationdb',
            old_name='roomname',
            new_name='message',
        ),
    ]
